export enum ErrorType {
	VALIDATION = "VALIDATION_ERROR",
	NOT_FOUND = "NOT_FOUND",
	UNAUTHORIZED = "UNAUTHORIZED",
	FORBIDDEN = "FORBIDDEN",
	BAD_REQUEST = "BAD_REQUEST",
	INTERNAL = "INTERNAL_SERVER_ERROR",
	DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE",
}
